version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hypothesis
    versions:
    - ">= 4.56.a, < 4.57"
  - dependency-name: hypothesis
    versions:
    - 6.8.4
