#!/usr/bin/env python3
from argparse import ArgumentParser

from siebenapp.system import load, dot_export, save


def print_dot(args):
    tree = load(args.db).goaltree.goaltree
    print(dot_export(tree))


def migrate(args):
    goals = load(args.db)
    save(goals, args.db)


def main():
    parser = ArgumentParser()
    subparsers = parser.add_subparsers(title="commands")

    parser_dot = subparsers.add_parser("dot")
    parser_dot.add_argument("db")
    parser_dot.set_defaults(func=print_dot)

    parser_migrate = subparsers.add_parser("migrate")
    parser_migrate.add_argument("db")
    parser_migrate.set_defaults(func=migrate)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
