name: CI build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    name: CI build on Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup pipenv
        run: pip install pipenv
      - name: Run tests
        run: make venv test mypy
        env:
          HYPOTHESIS_PROFILE: ci
